- build.gradle
- io-native/build.gradle
> Add configuration to publish IO native jar

- .github/workflows/build-master.yml
- README.md
- io-ballerina/build.gradle
- io-ballerina/src/io/open.bal
- io-ballerina/src/io/readable_csv_channel.bal
- io-ballerina/src/io/readable_data_channel.bal
- io-ballerina/src/io/readable_record_channel.bal
- io-ballerina/src/io/strings.bal
- io-ballerina/src/io/writable_csv_channel.bal
- io-ballerina/src/io/writable_data_channel.bal
- io-ballerina/src/io/writable_record_channel.bal
$subject
- Add README
- Add separate test configuration
- Fix public param issue
- SLP4
- Java 8
> Add test configurations and README

- io-ballerina/build.gradle
- io-native/src/main/java/org/ballerinalang/stdlib/io/channels/AbstractNativeChannel.java
- io-native/src/main/java/org/ballerinalang/stdlib/io/nativeimpl/ByteChannelUtils.java
- io-native/src/main/java/org/ballerinalang/stdlib/io/nativeimpl/CharacterChannelUtils.java
- io-native/src/main/java/org/ballerinalang/stdlib/io/nativeimpl/DataChannelUtils.java
- io-native/src/main/java/org/ballerinalang/stdlib/io/nativeimpl/GetTable.java
- io-native/src/main/java/org/ballerinalang/stdlib/io/nativeimpl/PrintUtils.java
- io-native/src/main/java/org/ballerinalang/stdlib/io/nativeimpl/ReadlnAny.java
- io-native/src/main/java/org/ballerinalang/stdlib/io/nativeimpl/RecordChannelUtils.java
- io-native/src/main/java/org/ballerinalang/stdlib/io/nativeimpl/Sprintf.java
- io-native/src/main/java/org/ballerinalang/stdlib/io/nativeimpl/WriteXml.java
- io-native/src/main/java/org/ballerinalang/stdlib/io/utils/IOUtils.java
- io-native/src/main/java/org/ballerinalang/stdlib/io/utils/PropertyUtils.java
- io-native/src/main/java/org/ballerinalang/stdlib/io/utils/Utils.java
- io-test-utils/src/main/java/org/ballerinalang/stdlib/io/testutils/PrintTestUtils.java
$subject
Disable API doc creation https://github.com/ballerina-platform/module-ballerina-io/issues/9
- SLP4
- Java 8
- macOS
> Migrate jBallerina Runtime APIs

- .github/workflows/pull-request.yml
- io-ballerina/src/io/print.bal
Fixes #7 
- Add `isolated` keyword
https://github.com/ballerina-platform/ballerina-lang/pull/25761
- SLP4
- Java8
- macOS
> Make print APIs isolated

- io-ballerina/build.gradle
> Enable doc creation

- .github/workflows/publish-release.yml
- .github/workflows/pull-request.yml
- build.gradle
- io-ballerina/build.gradle
- io-native/build.gradle
> Improve the GitHub release action 

- io-ballerina/src/nio/file-info.bal
- io-ballerina/src/nio/file.bal
- io-ballerina/src/nio/nio.bal
> Suggest new apis and make fileinfo a record

- build.gradle
> Remove unnecessary dependency of self repository

- io-ballerina/Ballerina.toml
$subject
https://github.com/ballerina-platform/module-ballerina-io/issues/23
> Update Java version in Ballerina.toml

- README.md
- io-native/src/main/java/module-info.java
- io-test-utils/src/main/java/module-info.java
$subject
Related to https://github.com/ballerina-platform/module-ballerina-io/issues/23
> Add license and update README with Java 11

- io-native/src/main/java/module-info.java
- io-native/src/main/java/org/ballerinalang/stdlib/io/channels/AbstractNativeChannel.java
- io-native/src/main/java/org/ballerinalang/stdlib/io/nativeimpl/ByteChannelUtils.java
- io-native/src/main/java/org/ballerinalang/stdlib/io/nativeimpl/CharacterChannelUtils.java
- io-native/src/main/java/org/ballerinalang/stdlib/io/nativeimpl/DataChannelUtils.java
- io-native/src/main/java/org/ballerinalang/stdlib/io/nativeimpl/GetTable.java
- io-native/src/main/java/org/ballerinalang/stdlib/io/nativeimpl/PrintUtils.java
- io-native/src/main/java/org/ballerinalang/stdlib/io/nativeimpl/ReadlnAny.java
- io-native/src/main/java/org/ballerinalang/stdlib/io/nativeimpl/RecordChannelUtils.java
- io-native/src/main/java/org/ballerinalang/stdlib/io/nativeimpl/Sprintf.java
- io-native/src/main/java/org/ballerinalang/stdlib/io/nativeimpl/WriteXml.java
- io-native/src/main/java/org/ballerinalang/stdlib/io/utils/IOConstants.java
- io-native/src/main/java/org/ballerinalang/stdlib/io/utils/IOUtils.java
- io-native/src/main/java/org/ballerinalang/stdlib/io/utils/PropertyUtils.java
- io-native/src/main/java/org/ballerinalang/stdlib/io/utils/Utils.java
- io-test-utils/src/main/java/module-info.java
- io-test-utils/src/main/java/org/ballerinalang/stdlib/io/testutils/PrintTestUtils.java
Refactor ballerina runtime api usages
> Migrate ballerina runtime apis

- README.md
> Update readme content of Issues and Projects

- .github/workflows/pull-request.yml
subtask of https://github.com/ballerina-platform/ballerina-standard-library/issues/569
> Change PR action to use user tokens

- io-ballerina/src/io/bytes/block_stream.bal
- io-ballerina/src/io/bytes/channel_byte_io.bal
- io-ballerina/src/io/bytes/file_byte_io.bal
- io-ballerina/src/io/bytes/readable_byte_channel.bal
- io-ballerina/src/io/bytes/writable_byte_channel.bal
- io-ballerina/src/io/character/channel_string_io.bal
- io-ballerina/src/io/character/file_string_io.bal
- io-ballerina/src/io/character/line_stream.bal
- io-ballerina/src/io/character/readable_character_channel.bal
- io-ballerina/src/io/character/string_reader.bal
- io-ballerina/src/io/character/writable_character_channel.bal
- io-ballerina/src/io/constants.bal
- io-ballerina/src/io/data/readable_data_channel.bal
- io-ballerina/src/io/data/writable_data_channel.bal
- io-ballerina/src/io/io_error.bal
- io-ballerina/src/io/open.bal
- io-ballerina/src/io/record/channel_csv_io.bal
- io-ballerina/src/io/record/csv_stream.bal
- io-ballerina/src/io/record/file_csv_io.bal
- io-ballerina/src/io/record/readable_csv_channel.bal
- io-ballerina/src/io/record/readable_record_channel.bal
- io-ballerina/src/io/record/writable_csv_channel.bal
- io-ballerina/src/io/record/writable_record_channel.bal
- io-ballerina/src/io/std/print.bal
- io-ballerina/src/io/std/read.bal
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/575
- Add missing information to the API docs
- Add more sample codes
> Improve API docs

- io-ballerina/build.gradle
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/631
- Java11
- SLP6
> Improve build task to copy the architecture diagram

- gradle.properties
> Upgrade the Ballerina version

- io-ballerina/init.bal
- io-native/src/main/java/org/ballerinalang/stdlib/io/channels/AbstractNativeChannel.java
- io-native/src/main/java/org/ballerinalang/stdlib/io/nativeimpl/ModuleUtils.java
- io-native/src/main/java/org/ballerinalang/stdlib/io/utils/IOConstants.java
- io-native/src/main/java/org/ballerinalang/stdlib/io/utils/IOUtils.java
- io-native/src/main/java/org/ballerinalang/stdlib/io/utils/Utils.java
$Subject
Resolves https://github.com/ballerina-platform/ballerina-lang/issues/26078
> Remove hard coded ballerina version in java code

- io-ballerina/channel_byte_io.bal
- io-ballerina/channel_csv_io.bal
- io-ballerina/channel_string_io.bal
- io-ballerina/readable_csv_channel.bal
$title
- macOS
- Java11
- SLP9
> Fix error construct expression change

- io-ballerina/tests/bytes_io.bal
- io-ballerina/tests/char_io.bal
- io-ballerina/tests/csv_io.bal
- io-ballerina/tests/data_io.bal
- io-ballerina/tests/io-test.bal
- io-ballerina/tests/record_io.bal
- io-ballerina/tests/string_io.bal
> Replace testerina function name with the pointer

- io-ballerina/build.gradle
> Update ballerina command to bal command
> Update ballerina command to bal command

- io-ballerina/block_stream.bal
- io-ballerina/csv_stream.bal
- io-ballerina/init.bal
- io-ballerina/line_stream.bal
- io-ballerina/open.bal
- io-ballerina/print.bal
- io-ballerina/read.bal
- io-ballerina/readable_byte_channel.bal
- io-ballerina/readable_character_channel.bal
- io-ballerina/readable_csv_channel.bal
- io-ballerina/readable_data_channel.bal
- io-ballerina/readable_record_channel.bal
- io-ballerina/tests/bytes_io.bal
- io-ballerina/tests/io-test.bal
- io-ballerina/writable_byte_channel.bal
- io-ballerina/writable_character_channel.bal
- io-ballerina/writable_data_channel.bal
- io-ballerina/writable_record_channel.bal
Related Issue: ballerina-platform/ballerina-lang#28034
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …
> Change the name of the `java` langlib module to `jballerina.java`

- gradle.properties
- io-ballerina/channel_byte_io.bal
- io-ballerina/channel_csv_io.bal
- io-ballerina/channel_string_io.bal
- io-ballerina/file_byte_io.bal
- io-ballerina/file_csv_io.bal
- io-ballerina/file_string_io.bal
- io-ballerina/readable_byte_channel.bal
- io-ballerina/readable_character_channel.bal
- io-ballerina/readable_csv_channel.bal
- io-ballerina/tests/bytes_io.bal
- io-ballerina/tests/csv_io.bal
> Fix for stream type change

- .github/workflows/build-master.yml
- .github/workflows/publish-release.yml
- .github/workflows/pull-request.yml
- .github/workflows/stdlib-workflow-trigger.yml
- io-ballerina/build.gradle
$subject
- SLAlpha-3
- macOS
- Java11
> Enable code coverage report publication

- io-ballerina/build.gradle
> Avoid running tests when publishing

- io-native/src/main/java/org/ballerinalang/stdlib/io/channels/base/DataChannel.java
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/415
- macOS
- Java11
- SLAlpha3
> Improve the byte array reverse logic in the Data channel

- io-native/src/main/java/org/ballerinalang/stdlib/io/utils/IOConstants.java
$subject 
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/926
> Remove I/O module and package hard coded constants

- io-ballerina/build.gradle
> Renames the extension of the package distribution file from balo to bala 
> Fixes ballerina-platform/ballerina-lang#28476
> Change ballerina archive extension to bala

- io-ballerina/build.gradle
This reverts commit c43a183bfc489d1998b1f7bdc79782fbf7dcc007.
> Revert "Replace balo with bala"

- io-ballerina/build.gradle
> Rename balo to bala

- io-ballerina/build.gradle
> Remove repetitive publish to central internal task

- build.gradle
- io-ballerina/build.gradle
- io-ballerina/io_error.bal
> Re-order Build Tasks to Publish to the Ballerina Central 

- io-ballerina/open.bal
The I/O API doc is showing the API without doc.
> Revert - Remove the unnecessary file open API docs

- .github/workflows/build-master.yml
- .github/workflows/pull-request.yml
- io-ballerina/build.gradle
> Remove publishing code-coverage testable JAR and archive JSON

- io-ballerina/build.gradle
> Add extracted bala in the zip artifact
> Fixes ballerina-platform/ballerina-lang#27763
> Add extracted bala in the zip artifact

- io-ballerina/build.gradle
> Add -c flag to build command
> Related to https://github.com/ballerina-platform/ballerina-lang/pull/29032
> Add -c flag to build command

- io-ballerina/io_error.bal
- io-ballerina/tests/bytes_io.bal
- io-ballerina/tests/csv_io.bal
- io-ballerina/tests/resources/csvResourceFile1.csv
- io-ballerina/tests/resources/csvResourceFile2.csv
- io-ballerina/tests/resources/stringResourceFile1.txt
- io-ballerina/tests/resources/stringResourceFile2.txt
- io-ballerina/tests/string_io.bal
- io-ballerina/tests/test_constants.bal
- io-native/src/main/java/org/ballerinalang/stdlib/io/nativeimpl/ByteChannelUtils.java
- io-native/src/main/java/org/ballerinalang/stdlib/io/utils/IOUtils.java
Subtask of https://github.com/ballerina-platform/ballerina-standard-library/issues/991
- Unit tests 
> Yes
- macOS
- Java 11
- SLA3
> Fix the custom error hierarchy 

- io-ballerina/Package.md
> Fix the broken I/O BBE link

- io-ballerina/block_stream.bal
- io-ballerina/channel_byte_io.bal
- io-ballerina/channel_csv_io.bal
- io-ballerina/channel_string_io.bal
- io-ballerina/csv_stream.bal
- io-ballerina/line_stream.bal
- io-ballerina/readable_csv_channel.bal
- io-ballerina/tests/bytes_io.bal
- io-ballerina/tests/console_io.bal
- io-ballerina/tests/conversion_io.bal
- io-ballerina/tests/csv_io.bal
- io-ballerina/tests/data_io.bal
- io-ballerina/tests/json_io.bal
- io-ballerina/tests/record_io.bal
- io-ballerina/tests/string_io.bal
- io-ballerina/tests/xml_io.bal
$subject
https://github.com/ballerina-platform/ballerina-lang/pull/29119
> Replace the var definitions with explicit types

- .github/workflows/build-timestamped-master.yml
> Add publish user credentials

- io-ballerina/build.gradle
> Stop timestamped version publishing to central

- build.gradle
- io-ballerina/build.gradle
> Strip stdlib dependency version

- .github/workflows/pull-request.yml
> Ignore version update tmp branch for push builds

- io-ballerina/Package.md
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/1318
> Add an introductory statement to the Package.md

- gradle.properties
- io-native/build.gradle
$title
Phase 02 - https://github.com/ballerina-platform/ballerina-standard-library/issues/1286
> Enable Jacoco report for I/O native tests

- io-ballerina/file_csv_io.bal
- io-ballerina/tests/bytes_io.bal
- io-ballerina/tests/console_io.bal
- io-ballerina/tests/csv_io.bal
- io-ballerina/tests/open_io.bal
- io-ballerina/tests/string_io.bal
- io-native/src/main/java/org/ballerinalang/stdlib/io/nativeimpl/ByteChannelUtils.java
- io-native/src/main/java/org/ballerinalang/stdlib/io/nativeimpl/CharacterChannelUtils.java
- io-native/src/main/java/org/ballerinalang/stdlib/io/utils/IOUtils.java
- io-native/src/test/java/org/ballerinalang/stdlib/io/channels/BlobIOChannelTest.java
- io-native/src/test/java/org/ballerinalang/stdlib/io/channels/FileIOChannelTest.java
- io-native/src/test/java/org/ballerinalang/stdlib/io/channels/TempFileIOChannelTest.java
- io-native/src/test/java/org/ballerinalang/stdlib/io/util/Base64ByteChannelTest.java
- io-native/src/test/java/org/ballerinalang/stdlib/io/util/Base64WrapperTest.java
- io-native/src/test/java/org/ballerinalang/stdlib/io/util/UtilsTest.java
Phase 03 - https://github.com/ballerina-platform/ballerina-standard-library/issues/1286
Fixes  https://github.com/ballerina-platform/ballerina-standard-library/issues/1286
> Improve the test coverage - phase 03

- io-ballerina/build.gradle
Set flag to enable Jacoco Coverage XML generation. Fixes https://github.com/ballerina-platform/ballerina-lang/issues/30381
> Set flag to enable Jacoco Coverage XML generation

- build-config/checkstyle/build.gradle
- build.gradle
- gradle.properties
- io-ballerina/build.gradle
Standardize build script of Ballerina module
> Apply Gradle Ballerina plugin for Ballerina module build script

- README.md
> Change the specific BBE URL to the main BBE page

- io-ballerina/Module.md
- io-ballerina/readable_csv_channel.bal
Addresses comment https://github.com/ballerina-platform/ballerina-standard-library/issues/1126#issuecomment-854342447
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/1127
> Temporarily remove the architecture diagram and doc comment fix

- .github/workflows/build-timestamped-master.yml
- .github/workflows/central-publish.yml
- .github/workflows/publish-release.yml
- .github/workflows/pull-request.yml
- build.gradle
- io-ballerina/Package.md
Related to:
ballerina-platform/ballerina-release#547 
ballerina-platform/ballerina-standard-library#1462
> Improve actions, Gradle, and Package.md

- io-ballerina/channel_byte_io.bal
- io-ballerina/channel_csv_io.bal
- io-ballerina/channel_string_io.bal
- io-ballerina/file_byte_io.bal
- io-ballerina/file_csv_io.bal
- io-ballerina/file_string_io.bal
- io-ballerina/open.bal
- io-ballerina/read.bal
- io-ballerina/readable_byte_channel.bal
- io-ballerina/readable_character_channel.bal
- io-ballerina/readable_csv_channel.bal
- io-ballerina/readable_record_channel.bal
- io-ballerina/string_reader.bal
- io-ballerina/tests/conversion_io.bal
> Remove unnecessary taint checks

- .github/workflows/pull-request.yml
- changelog.md
> Improve the PR action and update the changelog

- io-ballerina/tests/console_io.bal
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/1476
> Add test for printing strings with concatenation

- .github/workflows/build-timestamped-master.yml
- .github/workflows/pull-request.yml
- ballerina/Ballerina.toml
> Remove Group ID from Ballerina.toml

- ballerina/read.bal
> Update io:readln optional parameter with default value

- ballerina/build.gradle
> Add updateTomlFiles configurations

- .github/workflows/central-publish.yml
- .github/workflows/publish-release.yml
- .github/workflows/trivy-scan.yml
> Update the Trivy directory path

- ballerina/Ballerina.toml
- build-config/resources/Ballerina.toml
Related to - https://github.com/ballerina-platform/ballerina-standard-library/issues/2051
> Add meta description to the Ballerina.toml

- ballerina/block_stream.bal
- ballerina/channel_byte_io.bal
- ballerina/channel_csv_io.bal
- ballerina/channel_string_io.bal
- ballerina/csv_stream.bal
- ballerina/line_stream.bal
- ballerina/readable_csv_channel.bal
- ballerina/tests/bytes_io.bal
- ballerina/tests/conversion_io.bal
- ballerina/tests/csv_io.bal
- ballerina/tests/string_io.bal
- ballerina/tests/xml_io.bal
> Remove unused variables from implementation and tests

- .github/workflows/build-timestamped-master.yml
Related to - https://github.com/ballerina-platform/ballerina-standard-library/issues/2362
> Escape MD files and docs directory in master build

- ballerina/Dependencies.toml
- ballerina/tests/bytes_io.bal
- ballerina/tests/data_io.bal
- ballerina/tests/negative.bal
- ballerina/tests/record_io.bal
- ballerina/tests/string_io.bal
- native/src/main/java/io/ballerina/stdlib/io/nativeimpl/ByteChannelUtils.java
- native/src/main/java/io/ballerina/stdlib/io/nativeimpl/CharacterChannelUtils.java
- native/src/main/java/io/ballerina/stdlib/io/nativeimpl/DataChannelUtils.java
- native/src/main/java/io/ballerina/stdlib/io/nativeimpl/RecordChannelUtils.java
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/2261
> Add I/O related negative tests 

- load-tests/csv_processor/deployment/ingress.yaml
> Rename the service of ingress - load tests

- ballerina/file_string_io.bal
- docs/spec/spec.md
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/2254
> Add the specification for the I/O library

- docs/spec/spec.md
Address https://github.com/ballerina-platform/module-ballerina-io/pull/434/files#r773855104
> Fix the spec title

- load-tests/csv_processor/scripts/run.sh
> Reduce the concurrent users in load test running script

- examples/bow/Ballerina.toml
- examples/bow/README.md
- examples/bow/main.bal
- examples/bow/resources/data.txt
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/2257
Here, this is a BoW model generator implemented using Ballerina I/O operations. More information about the BoW model:
- https://machinelearningmastery.com/gentle-introduction-bag-words-model/
- https://en.wikipedia.org/wiki/Bag-of-words_model
Note, we cannot build this example here since it uses the regex library as a dependency, and it will create a circular dependency if we automatically run it during the build phase. Also, we use gRPC spec with certain modified as the sample raw text dataset.
> Add the example 02 - BoW generator

- examples/csv_processor/main.bal
- load-tests/csv_processor/src/app.bal
> Improve the CSV processor example and load test to use query expressions

- .github/workflows/process-load-test-result.yml
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/2618
Fixes this failure https://github.com/ballerina-platform/module-ballerina-io/actions/runs/1745417377
> Update load test dispatch workflow to process multiple load test results once

- load-tests/csv_processor/scripts/run.sh
- load-tests/csv_processor/src/app.bal
Due to this issue https://github.com/ballerina-platform/ballerina-lang/issues/34869
Once it is addressed we can roll this PR out.
> Revert the query expression changes

- .github/workflows/process-load-test-result.yml
- .github/workflows/trigger-load-tests.yml
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/2618
> Improve the load tests actions

- docs/spec/spec.md
> Add line splitting spaces to the spec description

- .github/workflows/process-load-test-result.yml
- .github/workflows/trigger-load-tests.yml
> Improve the load test actions to check codecov

- changelog.md
- docs/spec/spec.md
> Improve the spec introduction

- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
- gradle.properties
Reverts ballerina-platform/module-ballerina-io#511
> Revert "[Automated] Sync master after 1.2.1 release"

- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
- build-config/resources/Ballerina.toml
> Update the distribution version to 2201.0.1

- .github/workflows/publish-release.yml
Reverts ballerina-platform/module-ballerina-io#527
> Revert "Temporarily disabled the central publish"

- .github/workflows/central-publish.yml
- .github/workflows/publish-release.yml
- .github/workflows/trivy-scan.yml
- native/build.gradle
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/2902
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/2802
> Change the scan type of the Trivy scan and remove ballerina-core

- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
- gradle.properties
> Update lang version

- ballerina/tests/csv_io.bal
- ballerina/tests/negative.bal
- native/src/main/java/io/ballerina/stdlib/io/nativeimpl/CsvChannelUtils.java
- native/src/main/java/io/ballerina/stdlib/io/nativeimpl/RecordChannelUtils.java
- native/src/test/resources/datafiles/io/records/sample5d.csv
- native/src/test/resources/datafiles/io/records/sampleRef.csv
- native/src/test/resources/datafiles/io/records/sampleRefE.csv
Fixes: [3088](https://github.com/ballerina-platform/ballerina-standard-library/issues/3088)
> Fix the panic behaviour of fileReadCsv() and fileReadCsvAsStream() APIs

- ballerina/channel_csv_io.bal
- gradle.properties
Related to [#3128](https://github.com/ballerina-platform/ballerina-standard-library/issues/3128)
> Update std libs with 2201.2.0 lang version

- build-config/resources/Ballerina.toml
Related to : [#3117](https://github.com/ballerina-platform/ballerina-standard-library/issues/3117)
> Add details for native jars used in the standard library 

- .github/workflows/update_specs.yml
- ballerina/Ballerina.toml
- build-config/resources/Ballerina.toml
Related to [#3154](https://github.com/ballerina-platform/ballerina-standard-library/issues/3154)
> Add workflow to update specs

- .github/workflows/central-publish.yml
> Add missing sed command for multiple central environments support

- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
- ballerina/tests/bytes_io.bal
- build-config/resources/Ballerina.toml
- gradle.properties
- native/src/main/java/io/ballerina/stdlib/io/utils/Utils.java
- test-utils/src/main/java/io/ballerina/stdlib/io/testutils/PrintTestUtils.java
- test-utils/src/main/java/module-info.java
$subject
https://github.com/ballerina-platform/ballerina-standard-library/issues/3517
> Update io version for type-reference support

- ballerina/file_byte_io.bal
> Add missing white space

- ballerina/file_csv_io.bal
- ballerina/tests/csv_io.bal
- ballerina/tests/resources/csvResourceFile1WithMulltipleHeaders.csv
- changelog.md
- docs/spec/spec.md
- native/src/main/java/io/ballerina/stdlib/io/nativeimpl/RecordChannelUtils.java
Fixes:[4040](https://github.com/ballerina-platform/ballerina-standard-library/issues/4040)
> Update the code to support reading CSV files with multiple header lines 

- ballerina/tests/negative.bal
- changelog.md
- native/src/main/java/io/ballerina/stdlib/io/nativeimpl/RecordChannelUtils.java
Fixes: [3669](https://github.com/ballerina-platform/ballerina-standard-library/issues/3669)
> Update code to support only Record and String array of array type in CSV read

- .github/workflows/pull-request.yml
$subject
Related https://github.com/ballerina-platform/ballerina-standard-library/issues/4098
> Remove redundant retry steps in codecov upload

- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
- native/src/main/java/io/ballerina/stdlib/io/utils/Utils.java
This is to support the build for https://github.com/ballerina-platform/ballerina-standard-library/issues/4344
> Fix object getType() API usage

- ballerina/file_csv_io.bal
$subject
Fixes [4449](https://github.com/ballerina-platform/ballerina-standard-library/issues/4449)
> Fix not working examples related reading csv files.

- ballerina/Dependencies.toml
- gradle.properties
> Java17 migration

- .github/workflows/fossa_scan.yml
> Include GH credentials

- .github/workflows/fossa_scan.yml
> Fix env variables

- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
- build-config/resources/Ballerina.toml
- gradle.properties
> Bump minor version & update distribution

- ballerina/Package.md
Update the `Ballerina library` word.
> Update the `Ballerina library` word

- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
- changelog.md
- native/src/main/java/io/ballerina/stdlib/io/nativeimpl/CsvChannelUtils.java
- native/src/main/java/io/ballerina/stdlib/io/nativeimpl/WriteXml.java
- native/src/main/java/io/ballerina/stdlib/io/utils/IOConstants.java
- native/src/main/java/io/ballerina/stdlib/io/utils/PropertyUtils.java
- native/src/test/java/io/ballerina/stdlib/io/util/TestUtil.java
Closes ballerina-platform/ballerina-standard-library#4901.
> Make some Java classes proper utilities

- .github/workflows/build-timestamped-master.yml
- .github/workflows/build-with-bal-test-graalvm.yml
- .github/workflows/central-publish.yml
- .github/workflows/process-load-test-result.yml
- .github/workflows/publish-release.yml
- .github/workflows/pull-request.yml
- .github/workflows/trigger-load-tests.yml
- .github/workflows/trivy-scan.yml
- README.md
- ballerina/Ballerina.toml
- build-config/resources/Ballerina.toml
- gradle.properties
- native/build.gradle
- native/src/main/java/io/ballerina/stdlib/io/nativeimpl/ReadlnAny.java
- test-utils/build.gradle
> Migrate to Java 21

- gradle.properties
- native/src/main/java/io/ballerina/stdlib/io/nativeimpl/ReadlnAny.java
> Add yieldAndRun API changes

- gradle.properties
- native/src/main/java/io/ballerina/stdlib/io/nativeimpl/CsvChannelUtils.java
- native/src/main/java/io/ballerina/stdlib/io/nativeimpl/RecordChannelUtils.java
- native/src/main/java/io/ballerina/stdlib/io/nativeimpl/ToTable.java
- native/src/main/java/io/ballerina/stdlib/io/utils/PropertyUtils.java
- native/src/main/java/io/ballerina/stdlib/io/utils/Utils.java
> Migrate to new Runtime APIs

- native/src/main/java/io/ballerina/stdlib/io/nativeimpl/ToTable.java
> Add missing `getImpliedType` usage

- ballerina/Dependencies.toml
- gradle.properties
> Update versions for U11

- .gitignore
- ballerina/CompilerPlugin.toml
- ballerina/build.gradle
- build-config/resources/Ballerina.toml
- build-config/resources/CompilerPlugin.toml
- changelog.md
- compiler-plugin-tests/build.gradle
- compiler-plugin-tests/src/test/java/io/ballerina/stdlib/io/compiler/staticcodeanalyzer/ProcessOutputGobbler.java
- compiler-plugin-tests/src/test/java/io/ballerina/stdlib/io/compiler/staticcodeanalyzer/StaticCodeAnalyzerTest.java
- compiler-plugin-tests/src/test/resources/static_code_analyzer/ballerina_packages/rule1/Ballerina.toml
- compiler-plugin-tests/src/test/resources/static_code_analyzer/ballerina_packages/rule1/main.bal
- compiler-plugin-tests/src/test/resources/static_code_analyzer/expected_output/rule1.json
- compiler-plugin-tests/src/test/resources/testng.xml
- compiler-plugin/build.gradle
- compiler-plugin/src/main/java/io/ballerina/stdlib/io/compiler/Constants.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/io/compiler/IOCompilerPlugin.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/io/compiler/staticcodeanalyzer/IOCodeAnalyzer.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/io/compiler/staticcodeanalyzer/IOPathInjectionAnalyzer.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/io/compiler/staticcodeanalyzer/IORule.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/io/compiler/staticcodeanalyzer/RuleFactory.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/io/compiler/staticcodeanalyzer/RuleImpl.java
- compiler-plugin/src/main/java/module-info.java
- compiler-plugin/src/main/resources/rules.json
- gradle.properties
- settings.gradle
Reverts ballerina-platform/module-ballerina-io#1357
> Revert "Revert static rule change"

- .gitignore
- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- ballerina/build.gradle
- build-config/resources/Ballerina.toml
- build-config/resources/CompilerPlugin.toml
- changelog.md
- compiler-plugin-tests/build.gradle
- compiler-plugin-tests/src/test/java/io/ballerina/stdlib/io/compiler/staticcodeanalyzer/ProcessOutputGobbler.java
- compiler-plugin-tests/src/test/java/io/ballerina/stdlib/io/compiler/staticcodeanalyzer/StaticCodeAnalyzerTest.java
- compiler-plugin-tests/src/test/resources/static_code_analyzer/ballerina_packages/rule1/Ballerina.toml
- compiler-plugin-tests/src/test/resources/static_code_analyzer/ballerina_packages/rule1/main.bal
- compiler-plugin-tests/src/test/resources/static_code_analyzer/expected_output/rule1.json
- compiler-plugin-tests/src/test/resources/testng.xml
- compiler-plugin/build.gradle
- compiler-plugin/src/main/java/io/ballerina/stdlib/io/compiler/Constants.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/io/compiler/IOCompilerPlugin.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/io/compiler/staticcodeanalyzer/IOCodeAnalyzer.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/io/compiler/staticcodeanalyzer/IOPathInjectionAnalyzer.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/io/compiler/staticcodeanalyzer/IORule.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/io/compiler/staticcodeanalyzer/RuleFactory.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/io/compiler/staticcodeanalyzer/RuleImpl.java
- compiler-plugin/src/main/java/module-info.java
- compiler-plugin/src/main/resources/rules.json
- gradle.properties
- settings.gradle
> Add scan tool
