.github/workflows/build-master.yml, .github/workflows/daily-build.yml, .github/workflows/publish-release.yml, .github/workflows/pull-request.yml, io-ballerina/src/io/open.bal, io-ballerina/src/io/print.bal, io-ballerina/src/io/read.bal, io-ballerina/src/io/readable_byte_channel.bal, io-ballerina/src/io/readable_character_channel.bal, io-ballerina/src/io/readable_csv_channel.bal, io-ballerina/src/io/readable_data_channel.bal, io-ballerina/src/io/readable_record_channel.bal, io-ballerina/src/io/strings.bal, io-ballerina/src/io/tests/unit-tests/io-test.bal, io-ballerina/src/io/writable_byte_channel.bal, io-ballerina/src/io/writable_character_channel.bal, io-ballerina/src/io/writable_csv_channel.bal, io-ballerina/src/io/writable_data_channel.bal, io-ballerina/src/io/writable_record_channel.bal, io-native/build.gradle, io-native/src/main/java/org/ballerinalang/stdlib/io/nativeimpl/PrintUtils.java, io-native/src/main/java/org/ballerinalang/stdlib/io/nativeimpl/Sprintf.java
$subject
- Add class support
- Indent API doc comments
https://github.com/ballerina-platform/ballerina-lang/pull/25637
- SLP4
- Java 8
- macOS
=> Add Ballerina class support and fix API doc comment indentation

.github/workflows/build-master.yml, .github/workflows/daily-build.yml, .github/workflows/publish-release.yml, .github/workflows/pull-request.yml, build.gradle, gradle.properties, io-native/src/main/java/org/ballerinalang/stdlib/io/utils/IOConstants.java
As a part of standard library migration, the standard library module `SNAPSHOT` artifacts will be published to Github. This PR will enable the following:
- When there is an event of pushing changes to the `ballerina-lang` `master` branch, master branch build will be triggered eventually, and the `SNAPSHOT` artifacts will be published to the Github.
- When there is an event of a push the `master` branch in a module, on which this module depends on (if there's any), this module `master` branch build will be triggered and the `SNAPSHOT` artifacts will be published.
- When there is an event of a push on the `master` branch of this module, all the modules depending on this module will be triggered and the `SNAPSHOT` artifacts will be published.
Additionally this PR will restrict the release …
=> Update build and workflow scripts for releasing and publishing

.github/workflows/publish-release.yml, README.md, io-ballerina/build.gradle
There are 2 types of debug options we need to cover in standard libraries.
1. Debug a standard library with the native Java code
1. Debug a standard library with the Ballerina language
The `-Pdebug=5005` option, we previously had covered the 1st point. Here we enabled `-PbalJavaDebug=5005` covers the second point.
Address the issue in this thread: https://ballerina-platform.slack.com/archives/C9WMA6QDC/p1600844347001800
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
- Enabled -PbalJavaDebug option
- Minor fix to the release action
- SLP5
- Java8
- macOS
=> Add balJavaDebug option

io-ballerina/build.gradle, io-ballerina/src/io/bytes/block_stream.bal, io-ballerina/src/io/record/file_csv_io.bal, io-native/src/main/java/org/ballerinalang/stdlib/io/nativeimpl/ByteChannelUtils.java
$subject
To successfully make I/O operations from a socket channel.
- Make Block type public
- Create a BufferedInputStream when unavailable during byte operations
- Disable doc creation temporary due to this issue(https://github.com/ballerina-platform/ballerina-lang/issues/26733). Once it fixed, we can enable doc creation again.
- macOS
- Java 11
- SLP 6
=> Fix Block accessibility and BufferedInputStream issues

io-ballerina/src/io/bytes/channel_byte_io.bal, io-ballerina/src/io/bytes/file_byte_io.bal, io-ballerina/src/io/bytes/readable_byte_channel.bal, io-ballerina/src/io/character/channel_string_io.bal, io-ballerina/src/io/character/file_string_io.bal, io-ballerina/src/io/character/readable_character_channel.bal, io-ballerina/src/io/record/channel_csv_io.bal, io-ballerina/src/io/record/file_csv_io.bal, io-ballerina/src/io/record/readable_csv_channel.bal, io-ballerina/src/io/tests/unit-tests/bytes_io.bal, io-ballerina/src/io/tests/unit-tests/char_io.bal, io-ballerina/src/io/tests/unit-tests/csv_io.bal
Make all return types of the IO APIs consistent with taint checking.
- Add tainted return values
- Remove unnecessary null returns
https://github.com/ballerina-platform/module-ballerina-io/pull/31
- macOS
- Java11
- SLP6
=> Minor API fixes with returning nulls and taint checking

.gitignore, io-ballerina/build.gradle, io-ballerina/channel_byte_io.bal, io-ballerina/channel_csv_io.bal, io-ballerina/channel_string_io.bal
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/404#issuecomment-732729947
- Disable public accessibility of channel APIs
- Remove channel API docs
https://github.com/ballerina-platform/module-ballerina-io/pull/31
- SLP6
- Java11
=> Make channel APIs internal

io-ballerina/block_stream.bal, io-ballerina/channel_byte_io.bal, io-ballerina/channel_csv_io.bal, io-ballerina/channel_string_io.bal, io-ballerina/csv_stream.bal, io-ballerina/file_byte_io.bal, io-ballerina/file_csv_io.bal, io-ballerina/file_string_io.bal, io-ballerina/line_stream.bal, io-ballerina/readable_byte_channel.bal, io-ballerina/readable_character_channel.bal, io-ballerina/readable_csv_channel.bal, io-ballerina/tests/bytes_io.bal, io-ballerina/tests/char_io.bal, io-ballerina/tests/csv_io.bal
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/853
Add `io:Error?` to each of the following I/O streams:
- block stream
- line stream
- CSV stream
- Unit tests 
> Yes
https://github.com/ballerina-platform/module-ballerina-io/pull/31
- SLP9
- Java 11
- macOS
=> Enable Error? return to block, line, and CSV streams

io-native/src/main/java/org/ballerinalang/stdlib/io/utils/IOConstants.java
$subject
Have to update it because some other stdlibs use this constant to create readable and writable channels.
=> Upgrade the IO_PACKAGE_VERSION

io-ballerina/tests/bytes_io.bal, io-ballerina/tests/char_io.bal, io-ballerina/tests/csv_io.bal, io-native/src/main/java/org/ballerinalang/stdlib/io/utils/IOUtils.java
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/878
Enable `StandardOpenOption.TRUNCATE_EXISTING` option for writing operations.
- Unit tests 
> Yes
- macOS
- Java11
- SLAlpha1
=> Enable TRUNCATE_EXISTING for writing operations

io-native/src/main/java/org/ballerinalang/stdlib/io/nativeimpl/ByteChannelUtils.java
> $subject. With this fix, content is written to the  `ByteArrayOutputStream` up to the content length and convert the stream to an array. So can get rid of creating arrays which equal to the user given input(8196)
```ballerina
@test:Config {}
public function testSetByteStreamFromChannelAndGetByteStream() {
string content = "Hello Ballerina!";
string fileLocation = checkpanic createTemporaryFile("testFile", ".tmp", content);
io:ReadableByteChannel byteChannel = checkpanic io:openReadableFile(fileLocation);
stream<io:Block, io:Error> blockStream = checkpanic byteChannel.blockStream(8196);
Entity entity = new;
entity.setByteStream(blockStream);
var str = entity.getByteStream();
if (str is stream<byte[], io:Error>) {
record {|byte[] value;|}|io:Error? arr1 = str.next();
if (arr1 is record …
```
=> Avoid creating full length byte array

io-ballerina/build.gradle
> Publish `exec` file generate by the testerina as a Maven artifact and enable to publish testable jar files. With this PR exec file will be named as `io-ballerina-<version>-jacoco.exec` and testable jars will be named as `io-ballerina-<version>-testable-jars`
=> Publish Code Coverage Exec Files and Enable publishing testable jars

io-ballerina/Package.md
Due to the recent site changes of making swan lake default.
=> Change the BBE URL links as /swan-lake/learn->/learn

io-ballerina/constants.bal, io-ballerina/file_string_io.bal, io-ballerina/io_error.bal, io-ballerina/open.bal, io-ballerina/options.bal, io-ballerina/tests/resources/expectedXmlCharsFile4.xml, io-ballerina/tests/resources/expectedXmlCharsFile5.xml, io-ballerina/tests/resources/expectedXmlCharsFile6.xml, io-ballerina/tests/resources/expectedXmlCharsFile7.xml, io-ballerina/tests/resources/originalXmlContent.xml, io-ballerina/tests/xml_io.bal
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/941
Introduce XML writing options to the XML write API
- FileWriteOption - used to indicate whether to overwrite or append the content. Append only applicable when writing external parsed entities.
- XmlWriteOptions - to indicate XML doc type and entity type. The `xmlEntityType` to set the type of the document(document or external parsed entity).
- XmlDoctype - if an internal subset is specified, it is given priority over external ones and create the DOCTYPE declaration. If only the system is specified, it created a DOCTYPE declaration with SYSTEM. If public or (public and system) both specified, then it creates a DOCTYPE with PUBLIC.
- Unit tests 
> Yes
```ballerina 
import ballerina/io;
public function main() …
```
=> Introduce XML writing operations for DOCTYPE declaration writing

.github/workflows/publish-release.yml, build.gradle, gradle.properties, io-ballerina/build.gradle
- Subtask of https://github.com/ballerina-platform/ballerina-standard-library/issues/957
- Bump the next version to a minor alpha version
- Improve the build scripts and actions to publish the artifacts to the Ballerina central during a release
=> Enable publishing to the Ballerina central during the release

.github/workflows/pull-request.yml, io-ballerina/tests/bytes_io.bal, io-ballerina/tests/json_io.bal, io-ballerina/tests/text_io.bal, io-ballerina/tests/xml_io.bal, io-test-utils/src/main/java/org/ballerinalang/stdlib/io/testutils/EnvironmentTestUtils.java
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/183
- Enable UTF-8 encoding JVM options in the windows build
- Otherwise, it would take the default Windows encoding. Then the similar tests cannot be run in Windows and Linux because the expected values depend on the encoding type.
- Change the expected character count according to the OS
- In windows, a new line represents using two characters. Therefore, in windows expected character count is:
```
CharCountInWindows = CharCountInLinux + NoOfNewLineCharsInFile = CharCountInLinux + (NoOfLines - 1)
```
- Unit tests 
> Yes
- Java11
- SLAlpha4
- MacOS, Linux, and Windows
https://stackoverflow.com/questions/63445961/counting-characters-a-java-program-and-wc-yield-inconsistent-results
=> Fixed the windows build

io-ballerina/options.bal
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/983
https://github.com/ballerina-platform/module-ballerina-io/pull/77
- Ballerina SLAlpha4-SNAPSHOT
- macOS
- Java 11
=> Make `XmlDoctype` publicly accessible

io-ballerina/channel_string_io.bal, io-ballerina/file_string_io.bal, io-ballerina/writable_character_channel.bal, io-native/src/main/java/org/ballerinalang/stdlib/io/nativeimpl/CharacterChannelUtils.java
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/1032
Previously, we created the final XML to be written after concatenating the DOCTYPE block. The previous concatenation achieved using `xml:concat` API.
Recently, Ballerina language XML APIs pass these concatenation strings through an XML serializer. Therefore, these XML strings add special characters after serialization.
To solve that we need to directly write XML DOCTYPE block in the Java native level.
https://github.com/ballerina-platform/module-ballerina-io/pull/77
- Java 11
- Swan Lake 3
- macOS
=> Fix unnecessary character generation in the XML DOCTYPE

io-ballerina/channel.bal
Since the channel APIs are now private, we don't need these types to be public.
https://github.com/ballerina-platform/module-ballerina-io/pull/41
- macOS
- Java 11
=> Make abstract ReadableChannel and WritableChannel types private

io-ballerina/block_stream.bal, io-ballerina/channel_byte_io.bal, io-ballerina/channel_csv_io.bal, io-ballerina/channel_string_io.bal, io-ballerina/csv_stream.bal, io-ballerina/file_byte_io.bal, io-ballerina/file_csv_io.bal, io-ballerina/file_string_io.bal, io-ballerina/line_stream.bal, io-ballerina/open.bal, io-ballerina/readable_byte_channel.bal, io-ballerina/readable_character_channel.bal, io-ballerina/readable_csv_channel.bal, io-ballerina/readable_data_channel.bal, io-ballerina/readable_record_channel.bal, io-ballerina/string_reader.bal, io-ballerina/writable_byte_channel.bal, io-ballerina/writable_character_channel.bal, io-ballerina/writable_csv_channel.bal, io-ballerina/writable_data_channel.bal, io-ballerina/writable_record_channel.bal
Fix https://github.com/ballerina-platform/ballerina-standard-library/issues/1053
- Make I/O APIs isolated
- Change stream `forEach` with a `while` loop because the function inside `forEach` is accession `channels` outside the loop
https://github.com/ballerina-platform/module-ballerina-io/pull/8
- macOS
- Java 11
- Swan Lake 3
=> Make I/O read and write APIs isolated

io-ballerina/channel_byte_io.bal, io-ballerina/channel_csv_io.bal, io-ballerina/channel_string_io.bal, io-ballerina/file_byte_io.bal, io-ballerina/file_csv_io.bal, io-ballerina/file_string_io.bal, io-ballerina/print.bal, io-ballerina/readable_byte_channel.bal, io-ballerina/readable_character_channel.bal, io-ballerina/readable_csv_channel.bal, io-ballerina/readable_data_channel.bal, io-ballerina/readable_record_channel.bal, io-ballerina/tests/console_io.bal, io-ballerina/writable_character_channel.bal, io-ballerina/writable_data_channel.bal, io-ballerina/writable_record_channel.bal
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/1050
Add raw template support by implementing `toString()` APIs.
- Unit tests 
> Yes
```ballerina
string val = "John";
io:println(`Hello ${val}!!!`);
io:print(`Hello ${val}!!!`);
```
- macOS
- Java11
- SLA3
=> Improve the I/O print operations to support string templates

io-ballerina/channel_byte_io.bal, io-ballerina/channel_csv_io.bal, io-ballerina/channel_string_io.bal, io-ballerina/file_byte_io.bal, io-ballerina/file_csv_io.bal, io-ballerina/file_string_io.bal, io-ballerina/readable_byte_channel.bal, io-ballerina/readable_character_channel.bal, io-ballerina/readable_csv_channel.bal, io-ballerina/tests/bytes_io.bal, io-ballerina/tests/csv_io.bal, io-ballerina/tests/string_io.bal
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/1181
- Introduce nil completion to the I/O streams(lines, blocks, and CSV)
- Restore the previous `arr.toStream()` related tests
- Unit tests 
> Yes
- macOS
- Java 11
- SLAlpha 4
=> Adhere to the stream completion with nil changes

.github/workflows/central-publish.yml
To publish artifacts to Ballerina central if something went wrong in the release pipeline.
=> Add Ballerina publish to central workflow

README.md, io-ballerina/build.gradle
Incorporate all tests, build, and push into one task.
Then, we don't need to repetitively run update TOML and revert TOML tasks; running those two once will be enough.
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/1247
=> Fix the Ballerina.toml updating before the Ballerina push

.github/workflows/central-publish.yml, README.md, io-ballerina/build.gradle
Enabling `-PpublishToCentral=true` will only publish artifacts to the Ballerina central without publishing to Github.
This could be useful when something goes wrong in central publishing.
Related to https://github.com/ballerina-platform/module-ballerina-io/pull/133
=> Enable a parameter to indicate publish only to central

gradle.properties, io-ballerina/file_string_io.bal
As per the spec, the defaultable params should come before included-params.
Related to this https://github.com/ballerina-platform/ballerina-lang/issues/27818
=> Fix the parameter order

io-ballerina/tests/json_io.bal, io-ballerina/tests/xml_io.bal, io-native/src/main/java/org/ballerinalang/stdlib/io/utils/IOUtils.java
Previously, when there is an unidentified error, the I/O package returned an `error`. With this fix, it will return an `io:GenericError` which is a sub type of `io:Error`.
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/1316
=> Fix the unexpected error return by introducing package specific errors

io-ballerina/file_string_io.bal
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/1393
Note the new line at the end.
```
The Big Bang Theory
F.R.I.E.N.D.S
Game of Thrones
LOST
```
```
import ballerina/io;
public function main() returns error? {
io:println(check io:fileReadString("textfile.txt"));
}
```
Output is not as follows with a terminating carriage.
```
["The Big Bang Theory", "F.R.I.E.N.D.S", "Game of Thrones", "LOST", "\n"]
```
Ballerina output is an array without terminating carriage.
```
["The Big Bang Theory", "F.R.I.E.N.D.S", "Game of Thrones", "LOST"]
```
=> Include the terminating carriage information into the file string reading APIs docs

io-native/src/main/java/org/ballerinalang/stdlib/io/nativeimpl/CharacterChannelUtils.java
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/1392
Line separators for main operating systems are changed as follows:
- Unix based OS(Linux/MacOS): `\n` -> `\n`
- Windows: `\r\n` -> `\n`
=> Add newline replacement for platform-specific line separator

io-ballerina/constants.bal, io-ballerina/print.bal, io-ballerina/tests/console_io.bal, io-native/src/main/java/org/ballerinalang/stdlib/io/nativeimpl/PrintUtils.java, io-test-utils/src/main/java/org/ballerinalang/stdlib/io/testutils/PrintTestUtils.java
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/1394
```ballerina
io:fprint(io:stderr, "Unexpected error occurred");
io:fprint(io:stdout, "Unexpected error occurred");
io:fprintln(io:stderr, "Unexpected error occurred");
io:fprintln(io:stdout, "Unexpected error occurred");
```
=> Introduce fprint and fprintln APIs

ballerina/read.bal
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/1760
=> Make `io:readln` API input parameter optional

load-tests/csv_processor/src/Cloud.toml
K8s config maps can only hold up to 1MB. So, we have to use direct copying to the container instead of using a config map.
Related to - https://github.com/ballerina-platform/ballerina-performance-cloud/issues/3178
=> Use direct coping of CSV file due to config map limits

load-tests/csv_processor/scripts/run.sh
Even auth tests run with 10 users, need to try that value.
For 20 users and 1200 duration, the error rate is 57.54%
=> Reduce users and increase duration to find the threshold values

examples/bow/Ballerina.toml, examples/csv_processor/Ballerina.toml
Since we removed the observability modules from the ballerina-lang repo we have to disable the `observabilityIncluded` flag
https://github.com/ballerina-platform/ballerina-lang/issues/33195
=> Disable observability

.github/workflows/trigger-load-tests.yml
This load test cannot run using the intermediate pack, which create in the I/O module since the load test needs HTTP to run. So, we have to use the nightly distribution.
=> Remove the ZIP URL in the load test trigger action

.github/workflows/publish-release.yml
Due to the 1.2.1 release failure. We'll revert this back once the release is completed.
=> Temporarily disabled the central publish

README.md, ballerina/Ballerina.toml, ballerina/Dependencies.toml, ballerina/Package.md, changelog.md, docs/spec/spec.md
Related to [#3463](https://github.com/ballerina-platform/ballerina-standard-library/issues/3463)
=> Replace slack channel link with discord server link

ballerina/channel_csv_io.bal, ballerina/file_csv_io.bal, ballerina/tests/csv_io.bal, changelog.md, docs/spec/spec.md
This will fix the issue related to maintaining field order in `fileWriteCsvFromStream()` API
Fixes: [3399](https://github.com/ballerina-platform/ballerina-standard-library/issues/3399)
=> Update `fileWriteCsvFromStream` to maintain the order while writing

ballerina/tests/xml_io.bal
To comply with the change done for the xml parser to throw an error with the same message prefix  https://github.com/ballerina-platform/ballerina-lang/pull/40286#discussion_r1187280634.
=> Change `testReadInvalidXmlFile` test

ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, ballerina/tests/string_io.bal
As per [PR #7946](https://github.com/ballerina-platform/ballerina-library/pull/7946), the workflow files have been updated to prevent automatically converting LF to CRLF on Windows systems. As a result, the character count remains the same across both operating systems.
=> Fix the test case to read characters from a file
